In [31]:
import pandas as pd

In [32]:
# Load dataset
student_data = pd.read_csv("student.csv")

# Display first 5 rows
student_data.head()

,student_id,first_name,last_name,age,email,country,grade_math,grade_science,grade_english,Final_score
0,1,Kerrill,De Cleyne,24,kdecleyne0@furl.net,Venezuela,68,80,15,54
1,2,Krissie,Vittet,25,kvittet1@ustream.tv,Bulgaria,29,30,60,39
2,3,Hugibert,Haugg,21,hhaugg2@theguardian.com,New Zealand,76,0,55,43
3,4,Fancie,De Mars,18,fdemars3@parallels.com,China,82,88,90,86
4,5,Micki,O'Dowgaine,24,modowgaine4@livejournal.com,China,77,23,11,37

In [34]:
# Display dataset structure
student_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   student_id     1000 non-null   int64
 1   first_name     1000 non-null   object
 2   last_name      1000 non-null   object
 3   age            1000 non-null   int64
 4   email          1000 non-null   object
 5   country        1000 non-null   object
 6   grade_math     1000 non-null   int64
 7   grade_science  1000 non-null   int64
 8   grade_english  1000 non-null   int64
 9   Final_score    1000 non-null   int64
dtypes: int64(6), object(4)
memory usage: 78.3+ KB

In [35]:
# Check dataset shape
student_data.shape

(1000, 10)

In [36]:
# Check column names
student_data.columns

Index(['student_id', 'first_name', 'last_name', 'age', 'email', 'country',
       'grade_math', 'grade_science', 'grade_english', 'Final_score'],
      dtype='object')

In [37]:
# Statistical summary
student_data.describe()

,student_id,age,grade_math,grade_science,grade_english,Final_score
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,500.500000,21.536000,50.057000,48.335000,50.634000,49.341000
std,288.819436,2.275936,28.868723,29.229114,29.896619,16.801399
min,1.000000,18.000000,0.000000,0.000000,0.000000,7.000000
25%,250.750000,20.000000,24.000000,24.000000,24.000000,37.000000
50%,500.500000,21.000000,51.000000,47.000000,50.000000,49.500000
75%,750.250000,23.000000,74.000000,74.000000,77.250000,62.000000
max,1000.000000,25.000000,100.000000,100.000000,100.000000,92.000000

In [38]:
# Personal information dataset
personal_data = student_data[[
    'student_id',
    'first_name',
    'last_name',
    'age',
    'email',
    'country'
]]

# Academic dataset
academic_data = student_data[[
    'student_id',
    'grade_math',
    'grade_science',
    'grade_english',
    'Final_score'
]]

In [39]:
# Personal dataset
personal_data.head()

,student_id,first_name,last_name,age,email,country
0,1,Kerrill,De Cleyne,24,kdecleyne0@furl.net,Venezuela
1,2,Krissie,Vittet,25,kvittet1@ustream.tv,Bulgaria
2,3,Hugibert,Haugg,21,hhaugg2@theguardian.com,New Zealand
3,4,Fancie,De Mars,18,fdemars3@parallels.com,China
4,5,Micki,O'Dowgaine,24,modowgaine4@livejournal.com,China

In [40]:
# Academic dataset
academic_data.head()

   student_id  grade_math  grade_science  grade_english  Final_score
0           1          68             80             15           54
1           2          29             30             60           39
2           3          76              0             55           43
3           4          82             88             90           86
4           5          77             23             11           37

In [41]:
personal_data.to_csv("student_personal.csv", index=False)
academic_data.to_csv("student_academic.csv", index=False)

In [42]:
# Load separate datasets
personal = pd.read_csv("student_personal.csv")
academic = pd.read_csv("student_academic.csv")

In [43]:
personal.head()

,student_id,first_name,last_name,age,email,country
0,1,Kerrill,De Cleyne,24,kdecleyne0@furl.net,Venezuela
1,2,Krissie,Vittet,25,kvittet1@ustream.tv,Bulgaria
2,3,Hugibert,Haugg,21,hhaugg2@theguardian.com,New Zealand
3,4,Fancie,De Mars,18,fdemars3@parallels.com,China
4,5,Micki,O'Dowgaine,24,modowgaine4@livejournal.com,China

In [44]:
academic.head()

   student_id  grade_math  grade_science  grade_english  Final_score
0           1          68             80             15           54
1           2          29             30             60           39
2           3          76              0             55           43
3           4          82             88             90           86
4           5          77             23             11           37

In [45]:
personal.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   student_id  1000 non-null   int64
 1   first_name  1000 non-null   object
 2   last_name   1000 non-null   object
 3   age         1000 non-null   int64
 4   email       1000 non-null   object
 5   country     1000 non-null   object
dtypes: int64(2), object(4)
memory usage: 47.0+ KB

In [46]:
academic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   student_id     1000 non-null   int64
 1   grade_math     1000 non-null   int64
 2   grade_science  1000 non-null   int64
 3   grade_english  1000 non-null   int64
 4   Final_score    1000 non-null   int64
dtypes: int64(5)
memory usage: 39.2 KB

In [47]:
merged_data = pd.merge(
    personal,
    academic,
    on='student_id'
)

In [48]:
merged_data.head()

,student_id,first_name,last_name,age,email,country,grade_math,grade_science,grade_english,Final_score
0,1,Kerrill,De Cleyne,24,kdecleyne0@furl.net,Venezuela,68,80,15,54
1,2,Krissie,Vittet,25,kvittet1@ustream.tv,Bulgaria,29,30,60,39
2,3,Hugibert,Haugg,21,hhaugg2@theguardian.com,New Zealand,76,0,55,43
3,4,Fancie,De Mars,18,fdemars3@parallels.com,China,82,88,90,86
4,5,Micki,O'Dowgaine,24,modowgaine4@livejournal.com,China,77,23,11,37

In [49]:
merged_data.shape

(1000, 10)

In [50]:
merged_data['Total_Marks'] = (
    merged_data['grade_math'] +
    merged_data['grade_science'] +
    merged_data['grade_english']
)

In [51]:
merged_data['Average_Marks'] = (
    merged_data['Total_Marks'] / 3
)

In [52]:
merged_data.head()

,student_id,first_name,last_name,age,email,country,grade_math,grade_science,grade_english,Final_score,Total_Marks,Average_Marks
0,1,Kerrill,De Cleyne,24,kdecleyne0@furl.net,Venezuela,68,80,15,54,163,54.333333
1,2,Krissie,Vittet,25,kvittet1@ustream.tv,Bulgaria,29,30,60,39,119,39.666667
2,3,Hugibert,Haugg,21,hhaugg2@theguardian.com,New Zealand,76,0,55,43,131,43.666667
3,4,Fancie,De Mars,18,fdemars3@parallels.com,China,82,88,90,86,260,86.666667
4,5,Micki,O'Dowgaine,24,modowgaine4@livejournal.com,China,77,23,11,37,111,37.000000

In [53]:
merged_data.to_csv(
    'student_complete_data.csv',
    index=False
)

In [54]:
merged_data.sort_values(
    by='Final_score',
    ascending=False
).head(10)

,student_id,first_name,last_name,age,email,country,grade_math,grade_science,grade_english,Final_score,Total_Marks,Average_Marks
182,183,Terence,Rooson,20,trooson52@businessinsider.com,Vietnam,86,91,99,92,276,92.000000
27,28,Lloyd,Yeliashev,18,lyeliashevr@hud.gov,China,87,94,92,91,273,91.000000
231,232,Gaylord,Crumley,25,gcrumley6f@upenn.edu,Peru,99,88,84,90,271,90.333333
736,737,Abe,Bartolomeu,21,abartolomeukg@microsoft.com,Indonesia,78,97,96,90,271,90.333333
17,18,Ninetta,Carrane,20,ncarraneh@etsy.com,Slovenia,78,98,95,90,271,90.333333
150,151,Michelle,Tallant,20,mtallant46@cpanel.net,Philippines,99,96,77,90,272,90.666667
739,740,Giffy,Selcraig,21,gselcraigkj@cdc.gov,China,93,80,95,89,268,89.333333
530,531,Garnette,St Leger,25,gstlegereq@furl.net,China,78,98,88,88,264,88.000000
698,699,Devan,Barwell,25,dbarwellje@wsj.com,China,82,99,84,88,265,88.333333
575,576,Bailey,Deeney,20,bdeeneyfz@netvibes.com,China,76,89,96,87,261,87.000000

In [55]:
print("Average Math Score:", merged_data['grade_math'].mean())
print("Average Science Score:", merged_data['grade_science'].mean())
print("Average English Score:", merged_data['grade_english'].mean())

Average Math Score: 50.057
Average Science Score: 48.335
Average English Score: 50.634